#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

/usr/sbin/service php7.4-fpm start
/usr/sbin/service nginx start

usermod -aG www-data sail
chown sail:www-data -R /var/www
find /var/www -type d -exec chmod 2775 {} \;
find /var/www -name vendor -prune -o -type f -exec chmod 0664 {} \;

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
